import type { SiteContent } from "@/types/content";

/**
 * Social handles, in one place because the footer and the reserve band both
 * need them and a second copy is a second thing to get wrong.
 *
 * `.example` is the IANA-reserved placeholder name, used here for the same
 * reason the phone number and the WhatsApp number are unassigned: these must
 * read unmistakably as stand-ins and must not resolve to some real account that
 * would then be associated with a restaurant that does not exist. They are
 * structurally valid links — the pattern is demonstrated — that simply do not
 * lead anywhere.
 */
const HANDLE = "shabaneh.example";

const social = {
  instagram: { label: "اینستاگرام", href: `https://instagram.com/${HANDLE}` },
  telegram: { label: "تلگرام", href: `https://t.me/${HANDLE}` },
};

/**
 * PLACEHOLDER CONTENT.
 *
 * Every contact detail below is a stand-in. Phone, WhatsApp and email are
 * deliberately non-functional, and **the address is deliberately fictional**:
 * district level, no street number, no plaque, no coordinates and no map
 * anywhere on the site. That last one is not a styling convention — a demo that
 * sends a stranger to somebody's actual building is a real-world harm.
 *
 * Nothing here asserts a fact about a real business. Opening hours are the one
 * number stated plainly, because a restaurant that does not say when it is open
 * reads as unfinished, and because an opening time is not a claim about
 * quality, provenance or safety. Every numeral is authored in Latin digits and
 * rendered through `toFa()`.
 */
export const site: SiteContent = {
  brand: {
    name: "شبانه",
    latin: "SHABANEH",
    line: "یک سالن کوچک که فقط شب‌ها باز است.",
  },

  /**
   * Document title for the site as a whole. `titleTemplate` wraps whatever a
   * route supplies, so the name is written once here rather than being repeated
   * into every page's `<title>` by hand.
   */
  seo: {
    title: "شبانه — سالن غذاخوری شب",
    titleTemplate: "%s — شبانه",
    description:
      "شبانه یک سالن کوچک غذاخوری است که فقط شب‌ها باز است؛ نه خوراک در سه دسته، یک وعده در هر شب، با رزرو تلفنی.",
    /**
     * Generated by `scripts/generate-og.mjs` — a PNG, not an SVG, because no
     * social crawler renders an SVG share card.
     */
    ogImage: {
      src: "/media/og-card.png",
      alt: "نشان شبانه روی زمینهٔ تیرهٔ گرم",
      width: 1200,
      height: 630,
    },
  },

  /**
   * Three destinations, and the reservation as the one action.
   *
   * «رزرو میز» is deliberately not a fourth nav item: it is already the header
   * button, and a label appearing twice in one header reads as two different
   * things that happen to share a name.
   *
   * Hrefs are written from the site root so the header works on every page — a
   * bare `#reserve` resolves against whatever page the header happens to be
   * rendered on, which is nothing at all outside the homepage.
   */
  nav: [
    { label: "منو", href: "/products/" },
    { label: "فضا", href: "/gallery/" },
    { label: "دربارهٔ ما", href: "/about/" },
  ],

  headerCta: { label: "رزرو میز", href: "/about/#reserve" },

  contact: {
    city: "تهران",
    /** District level, invented, and with no number by design. */
    address: "تهران، محلهٔ نمونه",
    hours: "هر شب، 19 تا 24",
    phone: "021 — 0000 0000",
    phoneHref: "+982100000000",
    /**
     * WhatsApp number for click-to-chat, in Latin digits with no punctuation —
     * `wa.me` accepts nothing else, and Persian digits are not matched by `\d`.
     *
     * Deliberately not a real number. `wa.me` answers an unassigned number with
     * "this link is invalid" rather than opening a chat with a stranger, which
     * is the correct behaviour for a placeholder.
     */
    whatsapp: "989000000000",
    email: "reserve@shabaneh.example",
    instagram: { handle: `@${HANDLE}`, href: social.instagram.href },
  },

  social: [social.instagram, social.telegram],

  /**
   * Empty on purpose, and the footer hides the row while it is.
   *
   * A privacy policy and terms of use are the one category of content where
   * inventing plausible text is actively harmful. Add real entries here when
   * real policies exist and the row comes back with no change to any component.
   */
  legal: [],

  footer: {
    navHeading: "صفحه‌ها",
    contactHeading: "رزرو",
  },

  copyright: "© 1405 شبانه — تمام حقوق محفوظ است.",
};
